### ISSUE TITLE
Start without Avahi?

### ISSUE THREAD

**Issue by jamieshaw** [bjango/istatserverlinux#15]
Is it possible to start (or build the binary without Avahi)?

I'm not looking at enabling zeroconf support as this just leads me to having duplicate listings within iStat View to my manual configuration.  Unfortunately, I cannot simply remove the dependency packages as other software on the server requires Avahi.

Is there a command line to essentially _make without_?

**Comment by bjango-b** [comment]
You can add --with-no-avahi to the configure command
