### ISSUE TITLE
What happened to iStat View?

### ISSUE THREAD

**Issue by TD540** [bjango/istatserverlinux#21]
I want to test iStat Server for Linux, but it needs iStat View and I read on https://bjango.com it is no longer available for sale? Also seems nowhere to be downloaded...

What am I missing here?

**Comment by marcedwards** [comment]
Hi! I’m sorry, but we have discontinued iStat View. It’ll be available in the previous purchases section in the App Store app for people who have already bought it, but it’s not possible to buy it new.

**Comment by TD540** [comment]
But istatserverforlinux is still being worked on?

So I guess some kind of iStat View replacement must be in the works...

**Comment by marcedwards** [comment]
We’re not currently working on a new version of iStat View, sorry.
