### ISSUE TITLE
Failed configure on Debian Stretch

### ISSUE THREAD

**Issue by letlive** [bjango/istatserverlinux#4]
On Debian 9 (Stretch) configure script failed because Stretch doesn't support tlsv1. see below:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for ranlib... ranlib
checking for c++... c++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether c++ accepts -g... yes
checking for style of include used by make... none
checking dependency style of c++... none
checking for cc... cc
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking whether cc understands -c and -o together... yes
checking dependency style of cc... none
checking for ar... ar
checking if the compiler supports -Wall... yes
checking if the linker supports -rdynamic... yes
checking for inet_ntoa in -lnsl... yes
checking for socket in -lsocket... no
checking for xml2-config... xml2-config
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking libxml/parser.h usability... yes
checking libxml/parser.h presence... yes
checking for libxml/parser.h... yes
checking for xmlFileOpen... yes
checking openssl/x509.h usability... yes
checking openssl/x509.h presence... yes
checking for openssl/x509.h... yes
checking openssl/pem.h usability... yes
checking openssl/pem.h presence... yes
checking for openssl/pem.h... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking openssl/evp.h usability... yes
checking openssl/evp.h presence... yes
checking for openssl/evp.h... yes
checking openssl/err.h usability... yes
checking openssl/err.h presence... yes
checking for openssl/err.h... yes
checking for SSL_library_init in -lssl... no
configure: error: openssl/crypto not found or does not support tlsv1. you may need to update openssl or install openssl-dev/libssl-dev or a similar package

**Comment by letlive** [comment]
config.log include the following error report. Of course, libssl exists, however, SSL_library_init() was deprecated in OpenSSL 1.1.0:

```configure:5146: checking for SSL_library_init in -lssl
configure:5171: cc -o conftest -g -O2  -Wall -I /usr/local/include -I/usr/include/libxml2  -rdynamic -L /usr/local/lib conftest.c -lssl  -lnsl  -lpthread -lxml2 >&
5
/tmp/ccpCnC6e.o: In function `main':
/home/mzch/istatserver-3.0/conftest.c:39: undefined reference to `SSL_library_init'
collect2: error: ld returned 1 exit status
configure:5171: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "istatserver"
| #define PACKAGE_TARNAME "istatserver"
| #define PACKAGE_VERSION "3.0"
| #define PACKAGE_STRING "istatserver 3.0"
(snip)
| /* end confdefs.h.  */
|
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char SSL_library_init ();
| int
| main ()
| {
| return SSL_library_init ();
|   ;
|   return 0;
| }
configure:5180: result: no
configure:5278: error: openssl/crypto not found or does not support tlsv1. you may need to update openssl or install openssl-dev/libssl-dev or a similar package
```

**Comment by S1artie** [comment]
I ran into the same problem and found a workaround: build against the "legacy" package libssl1.0-dev, which is still available on Stretch.

**Comment by letlive** [comment]
I could see it on my server, but, yes, but it's "legacy". I'd like to build istatserver without a legacy library.

**Comment by Brusdeylins** [comment]
This bug is still open!
